# Generated by Django 6.0.7 on 2026-07-23 14:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('postal_code_prefix', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donor Service Area',
                'verbose_name_plural': 'Donor Service Areas',
            },
        ),
        migrations.AlterModelOptions(
            name='donorprofile',
            options={'verbose_name': 'Donor Profile', 'verbose_name_plural': 'Donor Profiles'},
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from recipients (0-5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='total_donations',
            field=models.PositiveIntegerField(default=0, help_text='Total number of donations made'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='total_food_donated_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total weight of food donated in kilograms', max_digits=10),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='verification_date',
            field=models.DateTimeField(blank=True, help_text='Date when verification was completed', null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes from verification process'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='address',
            field=models.TextField(help_text='Physical address for pickup/delivery'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='donor_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('grocery', 'Grocery Store'), ('event', 'Event Organizer'), ('individual', 'Individual'), ('other', 'Other')], help_text='Type of donor organization', max_length=20),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='email',
            field=models.EmailField(help_text='Contact email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this donor has been verified'),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='license_number',
            field=models.CharField(blank=True, help_text='Food handling license or registration number (if applicable)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='organization_name',
            field=models.CharField(help_text='Name of the organization or individual', max_length=200),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='phone_number',
            field=models.CharField(help_text='Contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='donor_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='donorprofile',
            index=models.Index(fields=['user'], name='donors_dono_user_id_171ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='donorprofile',
            index=models.Index(fields=['is_verified'], name='donors_dono_is_veri_9b0332_idx'),
        ),
        migrations.AddIndex(
            model_name='donorprofile',
            index=models.Index(fields=['donor_type'], name='donors_dono_donor_t_4c4162_idx'),
        ),
        migrations.AddIndex(
            model_name='donorprofile',
            index=models.Index(fields=['created_at'], name='donors_dono_created_cb29f1_idx'),
        ),
        migrations.AddField(
            model_name='donorservicearea',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='donors.donorprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='donorservicearea',
            unique_together={('donor', 'area_name')},
        ),
    ]
