# Generated by Django 6.0.7 on 2026-07-20 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('organization_name', models.CharField(max_length=200)),
                ('recipient_type', models.CharField(choices=[('shelter', 'Homeless Shelter'), ('food_bank', 'Food Bank'), ('community_kitchen', 'Community Kitchen'), ('ngo', 'Non-Governmental Organization'), ('church', 'Church/Religious Organization'), ('school', 'School/Educational Institution'), ('other', 'Other')], max_length=30)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('registration_number', models.CharField(help_text='Organization registration/license number', max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
