# Generated by Django 6.0.7 on 2026-07-23 14:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('postal_code_prefix', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recipient Service Area',
                'verbose_name_plural': 'Recipient Service Areas',
            },
        ),
        migrations.AlterModelOptions(
            name='recipientprofile',
            options={'verbose_name': 'Recipient Profile', 'verbose_name_plural': 'Recipient Profiles'},
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='accepts_perishable',
            field=models.BooleanField(default=True, help_text='Whether the organization accepts perishable food items'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from donors (0-5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='capacity_per_meal',
            field=models.PositiveIntegerField(default=50, help_text='Number of people that can be served per meal'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='has_cooking_facilities',
            field=models.BooleanField(default=True, help_text='Whether the facility has cooking capabilities'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='has_refrigeration',
            field=models.BooleanField(default=False, help_text='Whether the facility has refrigeration capabilities'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='preferred_delivery_days',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred days for delivery (0=Monday, 6=Sunday)'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='preferred_delivery_time_end',
            field=models.TimeField(blank=True, help_text='Preferred end time for deliveries', null=True),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='preferred_delivery_time_start',
            field=models.TimeField(blank=True, help_text='Preferred start time for deliveries', null=True),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='preferred_food_types',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred food types (from FOOD_TYPE_CHOICES)'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='restricted_food_types',
            field=models.JSONField(blank=True, default=list, help_text='List of restricted food types due to allergies, religious reasons, etc.'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='storage_capacity_kg',
            field=models.PositiveIntegerField(default=100, help_text='Maximum food storage capacity in kilograms'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='success_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of requests that were fulfilled (0-100)', max_digits=5),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='total_food_received_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total weight of food received in kilograms', max_digits=10),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='total_requests',
            field=models.PositiveIntegerField(default=0, help_text='Total number of donation requests made'),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='verification_date',
            field=models.DateTimeField(blank=True, help_text='Date when verification was completed', null=True),
        ),
        migrations.AddField(
            model_name='recipientprofile',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes from verification process'),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='address',
            field=models.TextField(help_text='Physical address for delivery/pickup'),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='contact_person',
            field=models.CharField(help_text='Primary contact person name', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='email',
            field=models.EmailField(help_text='Contact email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this recipient has been verified'),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='organization_name',
            field=models.CharField(help_text='Name of the organization', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='phone_number',
            field=models.CharField(help_text='Contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='recipient_type',
            field=models.CharField(choices=[('shelter', 'Homeless Shelter'), ('food_bank', 'Food Bank'), ('community_kitchen', 'Community Kitchen'), ('ngo', 'Non-Governmental Organization'), ('church', 'Church/Religious Organization'), ('school', 'School/Educational Institution'), ('other', 'Other')], help_text='Type of recipient organization', max_length=30),
        ),
        migrations.AlterField(
            model_name='recipientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recipient_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recipientprofile',
            index=models.Index(fields=['user'], name='recipients__user_id_4e513c_idx'),
        ),
        migrations.AddIndex(
            model_name='recipientprofile',
            index=models.Index(fields=['is_verified'], name='recipients__is_veri_13e00a_idx'),
        ),
        migrations.AddIndex(
            model_name='recipientprofile',
            index=models.Index(fields=['recipient_type'], name='recipients__recipie_4cddb3_idx'),
        ),
        migrations.AddIndex(
            model_name='recipientprofile',
            index=models.Index(fields=['created_at'], name='recipients__created_b57c0b_idx'),
        ),
        migrations.AddField(
            model_name='recipientservicearea',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='recipients.recipientprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='recipientservicearea',
            unique_together={('recipient', 'area_name')},
        ),
    ]
