# Generated by Django 6.0.7 on 2026-07-23 14:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('donors', '0002_donorservicearea_alter_donorprofile_options_and_more'),
        ('recipients', '0002_recipientservicearea_alter_recipientprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donation Image',
                'verbose_name_plural': 'Donation Images',
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_donation',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='verificationrequest',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='donationlisting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Donation Listing', 'verbose_name_plural': 'Donation Listings'},
        ),
        migrations.AlterModelOptions(
            name='matchrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Match Request', 'verbose_name_plural': 'Match Requests'},
        ),
        migrations.AddField(
            model_name='donationlisting',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='When this donation listing becomes available', null=True),
        ),
        migrations.AddField(
            model_name='donationlisting',
            name='available_until',
            field=models.DateTimeField(blank=True, help_text='When this donation listing expires (if different from food expiry)', null=True),
        ),
        migrations.AddField(
            model_name='donationlisting',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='When the donation was claimed', null=True),
        ),
        migrations.AddField(
            model_name='donationlisting',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='User who claimed this donation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationlisting',
            name='documentation_url',
            field=models.URLField(blank=True, help_text='URL to additional documentation (certificates, etc.)'),
        ),
        migrations.AddField(
            model_name='donationlisting',
            name='donor_profile',
            field=models.ForeignKey(blank=True, help_text='Donor profile (for performance optimization)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donors.donorprofile'),
        ),
        migrations.AddField(
            model_name='donationlisting',
            name='estimated_meals',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated number of meals this donation can provide', null=True),
        ),
        migrations.AddField(
            model_name='donationlisting',
            name='maximum_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Maximum quantity that can be claimed at once (null for no limit)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='donationlisting',
            name='minimum_quantity',
            field=models.DecimalField(decimal_places=3, default=0.001, help_text='Minimum quantity that can be claimed at once', max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='donationlisting',
            name='monetary_value_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated monetary value in local currency', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='donationlisting',
            name='special_handling_instructions',
            field=models.TextField(blank=True, help_text='Special instructions for handling (e.g., keep refrigerated, fragile)'),
        ),
        migrations.AddField(
            model_name='donationlisting',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight in kilograms (for reporting purposes)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='preferred_pickup_time',
            field=models.DateTimeField(blank=True, help_text='Preferred time for pickup/delivery', null=True),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='quantity_requested',
            field=models.DecimalField(decimal_places=3, default=0.001, help_text='Quantity of food requested', max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='quantity_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('grams', 'Grams'), ('lbs', 'Pounds'), ('ounces', 'Ounces'), ('liters', 'Liters'), ('milliliters', 'Milliliters'), ('pieces', 'Pieces'), ('portions', 'Portions'), ('boxes', 'Boxes'), ('bags', 'Bags'), ('containers', 'Containers'), ('pallets', 'Pallets')], default='kg', help_text='Unit of measurement for requested quantity', max_length=20),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='recipient_profile',
            field=models.ForeignKey(blank=True, help_text='Recipient profile (for performance optimization)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_requests', to='recipients.recipientprofile'),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='When the donor responded to the request', null=True),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='responded_by',
            field=models.ForeignKey(blank=True, help_text='Who responded to this request (donor or admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='response_message',
            field=models.TextField(blank=True, help_text='Response message from donor'),
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special instructions for pickup/delivery'),
        ),
        migrations.AlterField(
            model_name='donationlisting',
            name='description',
            field=models.TextField(help_text='Detailed description of the food items'),
        ),
        migrations.AlterField(
            model_name='donationlisting',
            name='donor',
            field=models.ForeignKey(help_text='User who created this donation', on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationlisting',
            name='expiry_date',
            field=models.DateTimeField(help_text='Date and time when the food expires and becomes unsafe'),
        ),
        migrations.AlterField(
            model_name='donationlisting',
            name='food_type',
            field=models.CharField(choices=[('prepared_meals', 'Prepared Meals'), ('fresh_produce', 'Fresh Produce'), ('bakery', 'Bakery Items'), ('dairy', 'Dairy Products'), ('meat_poultry', 'Meat & Poultry'), ('canned_goods', 'Canned Goods'), ('dry_goods', 'Dry Goods'), ('frozen', 'Frozen Foods'), ('beverages', 'Beverages'), ('other', 'Other')], help_text='Type of food being donated', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationlisting',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='List of photo URLs showing the food items'),
        ),
        migrations.AlterField(
            model_name='donationlisting',
            name='pickup_location',
            field=models.TextField(help_text='Specific location where food can be picked up'),
        ),
        migrations.AlterField(
            model_name='donationlisting',
            name='pickup_window_end',
            field=models.DateTimeField(help_text='Latest time when food can be picked up'),
        ),
        migrations.AlterField(
            model_name='donationlisting',
            name='pickup_window_start',
            field=models.DateTimeField(help_text='Earliest time when food can be picked up'),
        ),
        migrations.AlterField(
            model_name='donationlisting',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity of food available', max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='donationlisting',
            name='quantity_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('grams', 'Grams'), ('lbs', 'Pounds'), ('ounces', 'Ounces'), ('liters', 'Liters'), ('milliliters', 'Milliliters'), ('pieces', 'Pieces'), ('portions', 'Portions'), ('boxes', 'Boxes'), ('bags', 'Bags'), ('containers', 'Containers'), ('pallets', 'Pallets')], default='kg', help_text='Unit of measurement for quantity', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationlisting',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending Match'), ('matched', 'Matched'), ('claimed', 'Claimed'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='available', help_text='Current status of the donation', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', help_text='Current status of the request', max_length=20),
        ),
        migrations.AddIndex(
            model_name='donationlisting',
            index=models.Index(fields=['donor'], name='donations_d_donor_i_ac76bb_idx'),
        ),
        migrations.AddIndex(
            model_name='donationlisting',
            index=models.Index(fields=['status'], name='donations_d_status_aa29b2_idx'),
        ),
        migrations.AddIndex(
            model_name='donationlisting',
            index=models.Index(fields=['food_type'], name='donations_d_food_ty_ff59c5_idx'),
        ),
        migrations.AddIndex(
            model_name='donationlisting',
            index=models.Index(fields=['expiry_date'], name='donations_d_expiry__11ef2c_idx'),
        ),
        migrations.AddIndex(
            model_name='donationlisting',
            index=models.Index(fields=['pickup_window_start', 'pickup_window_end'], name='donations_d_pickup__2d032f_idx'),
        ),
        migrations.AddIndex(
            model_name='donationlisting',
            index=models.Index(fields=['created_at'], name='donations_d_created_ca16fe_idx'),
        ),
        migrations.AddIndex(
            model_name='donationlisting',
            index=models.Index(fields=['available_from', 'available_until'], name='donations_d_availab_cfc7e0_idx'),
        ),
        migrations.AddIndex(
            model_name='donationlisting',
            index=models.Index(fields=['pickup_location'], name='donation_location_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['donation'], name='donations_m_donatio_287956_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['recipient'], name='donations_m_recipie_444301_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['status'], name='donations_m_status_ae3895_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['requested_at'], name='donations_m_request_dfc329_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrequest',
            index=models.Index(fields=['status', 'requested_at'], name='donations_m_status_15011a_idx'),
        ),
        migrations.AddField(
            model_name='donationimage',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='donations.donationlisting'),
        ),
        migrations.AddField(
            model_name='donationimage',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_donation_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='VerificationRequest',
        ),
    ]
