# Generated by Django 6.0.1 on 2026-02-09 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_requests', to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donation')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngo_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
